export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'workspace',
        'credentials',
        'network',
        'identity',
        'audit',
        'cost',
        'budgets',
        'mcp',
        'agent',
        'skills',
        'evals',
        'batch',
        'guardrails',
        'observability',
        'sdk',
        'core',
        'pricing',
        'cli',
        'config',
        'charts',
        'terraform',
        'docs',
        'ci',
        'repo',
        'release',
        'deps',
        'examples',
      ],
    ],
    'header-max-length': [2, 'always', 100],
    'body-max-line-length': [0, 'always'],
    'subject-case': [0, 'never'],
  },
};
